version: '3'

services:
  db:
    image: heatsweepazaci.azurecr.io/postgres
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password1
  backend:
    image: heatsweepazaci.azurecr.io/heatsweepaz_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password1
    depends_on:
      - db
  frontend:
    image: heatsweepazaci.azurecr.io/heatsweepaz_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile 
    volumes:
      - ./frontend:/app
    ports:
      - "8080:5173"
    command: npm run dev
    
