# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2023-04-01 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heatsweep', '0002_auto_20230401_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'None'), ('a', 'A'), ('b', 'B'), ('hotspot', 'Hotspot')], default='none', max_length=6)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('heat_value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_turn', to='heatsweep.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_winner', to='heatsweep.Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='elo',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player_a', to='heatsweep.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_player_b', to='heatsweep.Player'),
        ),
        migrations.AddField(
            model_name='tile',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tile_game', to='heatsweep.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='a_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_a_start', to='heatsweep.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='b_start',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_b_start', to='heatsweep.Tile'),
        ),
        migrations.AddField(
            model_name='game',
            name='hotspot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_hotspot', to='heatsweep.Tile'),
        ),
    ]
