# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2023-04-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatsweep', '0004_auto_20230401_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
