# Generated by Django 2.2.28 on 2023-04-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatsweep', '0005_tile_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('a', 'A'), ('b', 'B'), ('h', 'Hotspot')], default='none', max_length=6),
        ),
    ]
