name: Deploy to ACI

on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up Docker Compose environment
        run: |
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          export POSTGRES_NAME=postgres
          export POSTGRES_USER=postgres
          export POSTGRES_PASSWORD=postgres
      - name: Build and push Docker Compose application
        run: |
          docker-compose build
          docker-compose push
      - name: Create ACI deployment
        uses: azure/container-instances-deploy@v1
        with:
          resource-group: my-resource-group
          dns-name-label: my-app
          containers: |
            [
              {
                "name": "db",
                "image": "postgres",
                "ports": [
                  {
                    "port": 5432
                  }
                ],
                "environmentVariables": [
                  {
                    "name": "POSTGRES_DB",
                    "value": "postgres"
                  },
                  {
                    "name": "POSTGRES_USER",
                    "value": "postgres"
                  },
                  {
                    "name": "POSTGRES_PASSWORD",
                    "value": "postgres"
                  }
                ]
              },
              {
                "name": "backend",
                "image": "myregistry.azurecr.io/myapp_backend:${{ env.IMAGE_TAG }}",
                "ports": [
                  {
                    "port": 8000
                  }
                ],
                "environmentVariables": [
                  {
                    "name": "POSTGRES_NAME",
                    "value": "postgres"
                  },
                  {
                    "name": "POSTGRES_USER",
                    "value": "postgres"
                  },
                  {
                    "name": "POSTGRES_PASSWORD",
                    "value": "postgres"
                  }
                ],
                "dependsOn": [
                  {
                    "name": "db",
                    "condition": "Success"
                  }
                ]
              },
              {
                "name": "frontend",
                "image": "myregistry.azurecr.io/myapp_frontend:${{ env.IMAGE_TAG }}",
                "ports": [
                  {
                    "port": 5173
                  }
                ],
                "environmentVariables": [
                  {
                    "name": "API_URL",
                    "value": "http://localhost:8000"
                  }
                ],
                "dependsOn": [
                  {
                    "name": "backend",
                    "condition": "Success"
                  }
                ]
              }
            ]
